### CH.1

머신러닝 개념 = APP을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법
- 지도학습 : 분류 / 회귀 / 추천시스템 / 시각,음성 감지, 인지 / 텍스트분석, NLP
- 비지도학습 : 클러스터링 / 차원축소 / 강화학습


1. 넘파이 : 수학 관련 패키지
   - 많은 과학 공학 패키지의 근간
   - 배열 기반의 연산 <-> 속도 빠름
   - 데이터 핸들링 기능을 제공하지만 pandas에는 미치지 못함
  
     1) 넘파이의 기반 데이터 타입 : ndarray
        - shape 함수
        - type() 함수
        - ndim 함수
       
     2) ndarray의 데이터 타입은 같은 데이터 타입만 가능
        - list를 ndarray로 바꾸는 방법 : np.array() 함수
        - dtype 함수 : ndarray 내 데이터 타입 확인 
        - astype() 함수 : ndarray 내 데이터 타입의 변경
       
     3) 그 외 함수
        - arange() : start / end --> start ~ (end-1)
        - zeros((m,n), dtype='int32')
        - ones((m,n))
        - reshape(m,n) : array의 차원과 크기 변경 <-> 차원을 높이지고 하고, 낮추기도 한다. 
              * ex) reshape(-1, 1) : 많이 사용함

     4) 인덱싱
        1. 단일값 : [] 인덱스 이용, 0부터 시작, - 이용하면 맨 뒤에서부터 추출 가능
           ex) [-1] : 마지막 값
           ex) [0,0] : 다차원 추출 가능

        2. 슬라이싱 : 연속 데이터 추출
           [start, stop]
           
        4. 팬시 인덱싱 : 리스트나 ndarray로 선택 범위 지정
       
        5. 불린 인덱싱 : 인덱스 값 대신 조건식 설정


     5) 정렬 : np.sort() / ndarray.sort() / 내림차순으로 정렬 --> np.sort()[::-1] 적용 

In [17]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ', array3.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)


In [19]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [21]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

In [25]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [29]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)


one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [33]:
array1 = np.arange(10)
print('array1: \n', array1)

array2 = array1.reshape(2,5)
print('array2: \n', array2)

array3 = array1.reshape(5,2)
print('array3: \n', array3)

array1.reshape(4,3)

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

In [35]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape: ', array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape: ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


In [37]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [41]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print('array3d: \n', array3d.tolist())    #ndarray를 list로 변경하는 함수

#3차원 ndarray를 2차원으로 변환 (고 -> 저)
array5 = array3d.reshape(-1,1)
print('array5 : \n', array5.tolist())
print('array5 shape : \n', array5.shape)

#1차원 ndarray를 2차원으로 변환 (저 -> 고)
array6 = array1.reshape(-1,1)
print('array6 : \n', array6.tolist())
print('array6 shape : ', array6.shape)

array3d: 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape : 
 (8, 1)
array6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape :  (8, 1)


In [43]:
array1 = np.arange(start=1, stop=10)
print('array1: ', array1)

value = array1[2]
print('value : ', value)
print(type(value))

print('맨 뒤의 값 : ', array1[-1], '맨 뒤에서 두번째 값 : ', array1[-2])

array1[0] = 9
array1[8] = 0
print('array1 : ', array1)

array1:  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>
맨 뒤의 값 :  9 맨 뒤에서 두번째 값 :  8
array1 :  [9 2 3 4 5 6 7 8 0]


In [45]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값 : ', array2d[0,0])
print('(row=0, col=1) index 가리키는 값 : ', array2d[0,1])
print('(row=1, col=0) index 가리키는 값 : ', array2d[1,0])
print('(row=2, col=2) index 가리키는 값 : ', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값 :  1
(row=0, col=1) index 가리키는 값 :  2
(row=1, col=0) index 가리키는 값 :  4
(row=2, col=2) index 가리키는 값 :  9


In [47]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [49]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [51]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d : \n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, : ] \n ', array2d[1:3, :])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, : ] 
  [[4 5 6]
 [7 8 9]]
array2d[:,:] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [53]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape : ', array2d[0].shape, 'array2d[1] shape : ', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape :  (3,) array2d[1] shape :  (3,)


In [60]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


In [62]:
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [64]:
array1d >5

array([False, False, False, False, False,  True,  True,  True,  True])

In [66]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 : ', array3)

불린 인덱스로 필터링 결과 :  [6 7 8 9]


In [81]:
indexes = np.array([5,6,7,8])

array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 : ', array4)

일반 인덱스로 필터링 결과 :  [6 7 8 9]


In [85]:
org_array = np.array([3,1,9,5])
print('원본 행렬 : ', org_array)

sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬: ', org_array)

sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 : ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬 :', org_array)

원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 :  None
org_array.sort() 호출 후 원본 행렬 : [1 3 5 9]


In [87]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 :', sort_array1_desc)

내림차순으로 정렬 : [9 5 3 1]


In [89]:
array2d = np.array([[8,12], [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬 : \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬 : \n', sort_array2d_axis1)

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


In [92]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))

print('행렬 정렬 시 원본 행렬의 인덱스  :', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스  : [1 0 3 2]


In [96]:
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 정렬 시 원본 행렬의 인덱스  :', sort_indices_desc)

행렬 정렬 시 원본 행렬의 인덱스  : [2 3 0 1]


In [100]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 :', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력 : ', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 : [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 :  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [106]:
A = np.array([[1,2,3], 
             [4,5,6]])

B = np.array([[7,8],
             [9,10], 
              [11,12]])

dot_product = np.dot(A,B)
print('행렬 내적 결과 : \n', dot_product)

행렬 내적 결과 : 
 [[ 58  64]
 [139 154]]


In [108]:
A = np.array([[1,2], [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬 : \n', transpose_mat)

A의 전치 행렬 : 
 [[1 3]
 [2 4]]
